- menu_name: "Uni/People"

# - name: "Contact"
#   url: "/contact/"
#   title: "Contact"

# - name: "RSS"
#   url: "/feed.xml"
#   title: "Subscribe to RSS Feed"

# - name: "Atom"
#   url: "/atom.xml"
#   title: "Subscribe to Atom Feed"


- name: "Shanghai International Studies University"
  url: "https://en.wikipedia.org/wiki/Shanghai_International_Studies_University"

- name: "Heilongjiang University"
  url: "https://en.wikipedia.org/wiki/Heilongjiang_University"

- name: "Lab PI: Prof. Xiaolin Zhou"
  url: "https://www.researchgate.net/profile/Xiaolin-Zhou-8"

- name: "Supervisor: Prof. Xiaoming Jiang"
  url: "https://www.researchgate.net/profile/Xiaoming-Jiang-3"